# Generated by Django 5.2.5 on 2025-08-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descritpion', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('Completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'Completed')], default=1, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
